# Lab 1 — Introduction to Natural Language Processing (NLP)

## Completed Tasks

This notebook contains only the required Lab 1 tasks and uses the provided **IMDB Dataset.csv**.

## Task #1 — Select a Dataset

**Dataset type:** CSV

**Selected dataset:** IMDB Dataset of 50K Movie Reviews

The dataset contains movie reviews and sentiment labels. Each review is labeled as either **positive** or **negative**, making the dataset suitable for Natural Language Processing and sentiment analysis.

## Task #2 — Open and Explore the Dataset

The provided `IMDB Dataset.csv` file is loaded below using pandas. The dataset is then inspected using the commands demonstrated in Lab 1.

In [1]:
import pandas as pd

# Load the provided IMDB dataset
df = pd.read_csv("IMDB Dataset.csv")

# Display the first 5 rows
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [2]:
# Display descriptive information about the dataset
df.describe(include="all")

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [3]:
# Display dataset structure, column names, data types, and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [4]:
# Count the number of reviews for each sentiment
df["sentiment"].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

## Lab 1 Result

The IMDB dataset was successfully loaded and explored.

- **Total records:** 50,000 movie reviews
- **Text column:** `review`
- **Target/label column:** `sentiment`
- **Sentiment classes:** `positive` and `negative`
- **Positive reviews:** 25,000
- **Negative reviews:** 25,000

The dataset is balanced and is appropriate for NLP sentiment-analysis tasks.